version: '3'
services:

  chirpbird-mysql:
      container_name: full_db_mysql
      build:
        context: .
        dockerfile: ./Dockerfile.mysql
      healthcheck:
        test: mysql --user=${DB_USER} --password=${DB_PASSWORD} -e 'SHOW DATABASES;'
        timeout: 20s
        retries: 10
      ports: 
        - 3306:3306
      environment: 
        - MYSQL_ROOT_HOST=${DB_HOST} 
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      volumes:
        - database_mysql:/var/lib/mysql
      networks:
        - chirpbird-networks
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - chirpbird-mysql 
    environment:
      - PMA_HOST=chirpbird-mysql # Note the "chirpbird-mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - chirpbird-networks

  chirpbird-server:
    container_name: chirpbird
    build: .
    entrypoint: ./main
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      chirpbird-mysql :
        condition: service_healthy          
    networks:
      - chirpbird-networks

  chirpbird-client:
    container_name: client-chirpbird
    build: client-side/.
    ports: 
      - 3000:80 
    restart: on-failure
    volumes:
      - './:/app'
      - '/app/node_modules'
    depends_on:
      - chirpbird-server         
    networks:
      - chirpbird-networks


volumes:
  api:
  database_mysql:                  

networks:
  chirpbird-networks:
    driver: bridge